# Generated by Django 5.0.1 on 2024-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('user_first_name', models.TextField()),
                ('user_last_name', models.TextField()),
                ('user_password', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='status',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='tasks',
            new_name='task',
        ),
    ]
